INSERT INTO teachers (teacherID, first_name, last_name, email, department, added_by) VALUES
(1, 'Hamlin', 'Norcott', 'hnorcott0@blogs.com', 'Medicine', 'admin'),
(2, 'Hermann', 'Ratie', 'hratie1@cnet.com', 'Business', 'admin'),
(3, 'Candy', 'Croll', 'ccroll2@netvibes.com', 'Medicine', 'admin'),
(4, 'Elinor', 'Newling', 'enewling3@miitbeian.gov.cn', 'Arts and Sciences', 'admin'),
(5, 'Nester', 'Messitt', 'nmessitt4@paginegialle.it', 'Arts and Sciences', 'admin'),
(6, 'Malcolm', 'Penrith', 'mpenrith5@constantcontact.com', 'Arts and Sciences', 'admin'),
(7, 'Debora', 'Overel', 'doverel6@about.me', 'Business', 'admin'),
(8, 'Joyann', 'Wildor', 'jwildor7@mtv.com', 'Engineering', 'admin'),
(9, 'Devy', 'Dumbare', 'ddumbare8@histats.com', 'Medicine', 'admin'),
(10, 'Joletta', 'Mossop', 'jmossop9@bigcartel.com', 'Medicine', 'admin'),
(11, 'Mada', 'Vauls', 'mvaulsa@statcounter.com', 'Business', 'admin'),
(12, 'Blisse', 'Pearse', 'bpearseb@macromedia.com', 'Business', 'admin'),
(13, 'Eulalie', 'Vian', 'evianc@ifeng.com', 'Medicine', 'admin'),
(14, 'Howard', 'Farebrother', 'hfarebrotherd@amazon.co.jp', 'Medicine', 'admin'),
(15, 'Andria', 'Joyes', 'ajoyese@state.tx.us', 'Engineering', 'admin'),
(16, 'Gun', 'Klimentov', 'gklimentovf@arstechnica.com', 'Business', 'admin'),
(17, 'Aubrey', 'MacPaike', 'amacpaikeg@flavors.me', 'Engineering', 'admin'),
(18, 'Merrie', 'Gillford', 'mgillfordh@cbsnews.com', 'Medicine', 'admin'),
(19, 'Karoly', 'Battleson', 'kbattlesoni@de.vu', 'Arts and Sciences', 'admin'),
(20, 'Melania', 'Savary', 'msavaryj@youtu.be', 'Arts and Sciences', 'admin'),
(21, 'Jodee', 'Brayshay', 'jbrayshayk@ovh.net', 'Engineering', 'admin'),
(22, 'Ronnica', 'Davidai', 'rdavidail@reddit.com', 'Business', 'admin'),
(23, 'Gale', 'Doumerque', 'gdoumerquem@prlog.org', 'Business', 'admin'),
(24, 'Lowe', 'McAlister', 'lmcalistern@stanford.edu', 'Arts and Sciences', 'admin'),
(25, 'Konrad', 'Winterson', 'kwintersono@diigo.com', 'Business', 'admin'),
(26, 'Emelina', 'Driscoll', 'edriscollp@constantcontact.com', 'Arts and Sciences', 'admin'),
(27, 'Isabella', 'Sword', 'iswordq@mac.com', 'Arts and Sciences', 'admin'),
(28, 'Rosabelle', 'Barraclough', 'rbarracloughr@ovh.net', 'Engineering', 'admin'),
(29, 'Jenica', 'Martineau', 'jmartineaus@netvibes.com', 'Medicine', 'admin'),
(30, 'Kati', 'Prudence', 'kprudencet@yandex.ru', 'Engineering', 'admin');
